# Rime default settings
# encoding: utf-8

config_version: '0.40'

schema_list:
  - schema: double_pinyin_flypy       # 简单鹤挂接小鹤双拼  
  - schema: luna_pinyin                     # 朙月拼音（白霜词库）
  - schema: JDhe                               # 简单鹤 （乱序字根音形） 
  - schema: whale_double_flypy       # 鲸凉鹤挂接小鹤双拼   
  - schema: whaleHe                            # 鲸凉鹤（小鹤音形官版字根）
  - schema: tiger                                # 虎码  
#  - schema: t9_pinyin                      # 手机专用 九宫格方案
#  - schema: t17_pinyin_double       # 手机专用 17键乱序双拼

switcher:
  caption: 〔方案選單〕
  hotkeys:
    - Control+grave
    - Control+Shift+grave
    - F4
  save_options:
    - ascii_punct
    - traditionalization
    - emoji
    - full_shape
    - search_single_char
    - simplification              # 简繁切换
    - emoji                     # emoji表情开关
    - single_char_only         # 单字模式
    - embeded_cands         # 字词嵌入编辑栏
    - no_quick_words         # 简码词开关
    - spelling.off          # 虎码拆字注释  拆隐
    - spelling.lv1          # 虎码拆字注释  拆显
    - spelling.lv1.1          # 虎码拆字注释  编显 (虎码)
    - spelling.lv1.2          # 虎码拆字注释  音显 (带声调全拼)       
    - spelling.lv2          # 虎码拆字注释  拆+编
    - spelling.lv3          # 虎码拆字注释 拆+编+音
    - autocompletion_filter      # 编码补全提示
    - pinyinhint                          # 拼音滤镜开关
    - single_char_only_for_full_code        # 四码单字开关
    - chaifen        # 简单鹤拆字注释开关
    - inflexible    # 固词或动词开关
    - block_words_enabled   # 是否屏蔽指定的字词列表
    - prediction                 #输入联想预测
  fold_options: true
  abbreviate_options: true
  option_list_separator: '／'

menu:
  page_size: 5

punctuator:
  full_shape:
    __include: punctuation:/full_shape
  half_shape:
    __include: punctuation:/half_shape

key_binder:
  bindings:
    __patch:
      - config_base:/key_config/options_toggle
      - config_base:/key_config/tab_Page
      - config_base:/key_config/keys

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

# 中西文切换
#
# good_old_caps_lock:
# true   切换大写
# false  切换中英
# macOS 偏好设置的优先级更高，如果勾选【使用大写锁定键切换“ABC”输入法】则始终会切换输入法。
#
# 切换中英：
# 不同的选项表示：打字打到一半时按下了 CapsLock、Shift、Control 后：
# commit_code  上屏原始的编码，然后切换到英文
# commit_text  上屏拼出的词句，然后切换到英文
# clear        清除未上屏内容，然后切换到英文
# inline_ascii 切换到临时英文模式，按回车上屏后回到中文状态
# noop         屏蔽快捷键，不切换中英，但不要屏蔽 CapsLock
ascii_composer:
  good_old_caps_lock: true  # true | false
  switch_key:
    Caps_Lock: clear      # commit_code | commit_text | clear
    Eisu_toggle: clear      # commit_code | commit_text | clear
    Shift_L: inline_ascii  # commit_code | commit_text | inline_ascii | clear | noop
    Shift_R: noop         # commit_code | commit_text | inline_ascii | clear | noop
    Control_L: noop       # commit_code | commit_text | inline_ascii | clear | noop
    Control_R: noop       # commit_code | commit_text | inline_ascii | clear | noop  
